### ISSUE TITLE
Fails when dependency not installed

### ISSUE THREAD

**Issue by svenanders** [peerigon/updtr#23]
When _updtr_ tries updating a module that's not installed, it failes with this command:

```bash
Error: Command failed: /bin/sh -c npm i babel-tape-runner@undefined --save-dev
```

running _npm outdated_ I can see that the dependency is currently missing:
![image](https://cloud.githubusercontent.com/assets/1560743/12372001/71003fd2-bc47-11e5-9d4e-f3a4efe7f197.png)

running _npm i_ before _updtr_ obviously fixes the issue, so it's not really a problem - just wanted to let you know.

**Comment by matthaias** [comment]
Thanks. 

Were your tests failing in this case? *updtr* tries to install the `current` version then. If the package was not installed before, there is no version to install (`undefiend`). Maybe we should just skip not installed packages.

**Comment by svenanders** [comment]
Yep - they were failing because _tape_ was missing. I guess it was kind of an odd set of circumstances.

**Comment by matthaias** [comment]
`v0.1.9` checks now if some modules are missing.
