### ISSUE TITLE
Keep formatting in package.json

### ISSUE THREAD

**Issue by mistadikay** [peerigon/updtr#24]
Hey there! Love your module, but have a couple of concerns. One of them is described in [this issue](https://github.com/peerigon/updtr/issues/14), so let me jump to the second one.

Is there a way to save formatting in `package.json`? We divide dependencies into the blocks separated by empty line, for example we have unit-testing dependencies, code linting dependencies, webpack-related, babel-related, etc. `updtr` though squashes them together and sorts alphabetically which breaks the structure. Any way to put it under the special flag like `--keep-structure` or something? Thanks.

**Comment by matthaias** [comment]
Sorry, but i think this is not possible at the moment. The reason is that we update the packages via the `npm install` command in the background. This command sorts the packages alphabeticall. I don't see a possibility to change this behavior at the moment, or do you have an idea?

**Comment by mistadikay** [comment]
Yeah, I investigated it a little bit and it looks like we will never see this kind of functionality from npm side (https://github.com/npm/npm/pull/3299 + https://github.com/npm/npm/pull/3180) since _it will add unnecessary complexity to CLI_.

I have an idea how to make it possible with a tool like https://github.com/ljharb/json-file-plus, but it supports only indentation formatting at the moment and I'm not sure it would be easy to implement empty lines preserving there. I'll close this issue for now. Thanks
