### ISSUE TITLE
Add option to specific custom npm registry 

### ISSUE THREAD

**Issue by egoist** [peerigon/updtr#25]
eg: `updtr --registry https://registry.npm.taobao.org`

**Comment by rbartoli** [comment]
@egoist are you interested in specifying a different registry than the one set in `npm config`?

**Comment by egoist** [comment]
@rbartoli Yes, I use the default registry to do things like `npm publish`, but use `npm --registry http://registry.in.china` to make installing faster in my area. And lots of people do like so here. 

However this is not a high priority issue 😅

**Comment by matthaias** [comment]
So you are installing your packages with `npm install --registry http://your.registry packageName` right? I think you forgot the word `install`, or i think about something else :)

**Comment by matthaias** [comment]
Published as `v0.1.13`

**Comment by egoist** [comment]
Wow, thanks! 😁
