### ISSUE TITLE
rvm not recognized as internal command on Windows 10

### ISSUE THREAD

**Issue by drazik** [peerigon/updtr#26]
Hello,

I was trying to use updatr on a project that use outdated dependencies, but I had this error : 

```
λ updatr --help
Updating node and npm
Updating brew
Updating rvm
updatr complete.
C:\Users\cperois\AppData\Roaming\npm\node_modules\updatr\bin\updatr:23
  if (err) throw err;
           ^

Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "rvm get stable"
'rvm' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

The error is in french, but it mean " 'rvm' is not recognized as an internal or external command, an executable or a commands file".

Am I doing something wrong ?

Thanks.

**Comment by meaku** [comment]
It's `updtr` not `updatr`. Seems like you installed https://www.npmjs.com/package/updatr.

**Comment by drazik** [comment]
Oh sorry for this mistake ! Thanks a lot !

**Comment by mo** [comment]
FWIW; I ran into the same issue (but using Linux) ... it would be nice if @johnotander removed or renamed the "updatr" package

**Comment by johnotander** [comment]
This is the first time this has been brought to my attention. I've added a deprecation message to `updatr`:

```
~/c
❯ npm i -g updatr
npm WARN deprecated updatr@0.1.1: This project is no longer maintained, you probably meant to install updtr (npm i -g updtr)
```

Thanks.

**Comment by mo** [comment]
@johnotander awesome, thanks a lot..
