### ISSUE TITLE
update dependencie fails

### ISSUE THREAD

**Issue by stephanfriedrich** [peerigon/updtr#33]
Hi at first, thx for you nice tool.

I get some strange behaviour with my packages.
**I have to run `updtr` twice to update all dependencies.**

My local installed Packages:
```
  "devDependencies": {
    "grunt": "^0.4",
    "grunt-contrib-watch": "^0.6",
    "grunt-contrib-compass": "^1",
    "grunt-contrib-imagemin": "^0.8",
    "grunt-contrib-uglify": "^0.9",
    "grunt-jsdoc": "^0.6"
  }
```
[1] i run `updtr`, 
-- the update for *grunt package* fails
-- all the other packages updates to its latest version
[2]  i run `updtr`again, 
-- now *grunt package* updates to latest version

**Question:**
is this behaviour correct?

**Comment by matthaias** [comment]
Hey @stephanfriedrich. Was that a problem only in this case, or failed _updtr_ in more cases? Maybe the new grunt version didn't work with one version of the grunt plugins. This could be the reason that it was possible to update grunt itself after all plugins were updated.

**Comment by matthaias** [comment]
Please let me know if you still have problems @stephanfriedrich. I close this for now.
