### ISSUE TITLE
unfortunate, handling error with beta / next modules

### ISSUE THREAD

**Issue by leecade** [peerigon/updtr#35]
I am not sure this is a bug or a strategy, It's very dangerous and against my will

```
-    "koa": "^2.0.0",
+    "koa": "^1.2.0",

-    "koa-static": "^3.0.0",
+    "koa-static": "^2.0.0",

-    "webpack": "^2.1.0-beta.5"
+    "webpack": "^1.13.0"
```

**Comment by matthaias** [comment]
At the moment updtr tries to install the version which is tagged as `latest`. But i think this is the same as https://github.com/peerigon/updtr/issues/21, right? I think i can close this an we will find a solution for that. If not, we will reopen this of course.
