### ISSUE TITLE
Trouble rolling back

### ISSUE THREAD

**Issue by GantMan** [peerigon/updtr#38]
![image](https://cloud.githubusercontent.com/assets/997157/15439388/5a93a73c-1e96-11e6-9cfd-e0e7423a0709.png)

Not sure why this fails, but just reporting it.

I got around it with `updtr --exclude react`

**Comment by GantMan** [comment]
Actually, I didn't get around it.  Saying --exclude react, skips anything that begins with `react` it seems.

**Comment by matthaias** [comment]
You are right, it should not exclude everything starting with babel, i just published a bugfix with `v0.1.15`. Can you please give it a try?

I am wondering, why updtr is trying to execute `/bin/sh -c npm i react@0.14.8 --save-dev`. Can you give me more information about your OS, node and npm? Did it work in other projects?

**Comment by GantMan** [comment]
Hi @matthaias - I moved on from this for now, but will report back here if it happens again.  

`updtr` has worked great for me!   I'm a huge fan.  It's basically how I update every week.
