### ISSUE TITLE
prevent downgrading to stable version when package.json specifies a pre-release version

### ISSUE THREAD

**Issue by travi** [peerigon/updtr#43]
I'm currently using the alpha version of istanbul to collect coverage information with es6 code. However, when I run `updtr`, it always replaces it with the latest stable version. I understand not wanting to "upgrade" those projects that have specified a stable version to the pre-release, but since I have specified the alpha, I'd prefer not to be downgraded either.

I'm not sure if `dist-tags` or semver is the safer way to identify a pre-release, so I'll leave that decision to you, but some interesting things about the specific istanbul case are:
* they do not tag the alpha version with an `alpha` tag, but rather a `next` tag
* the alpha that is tagged with `next` is not the latest alpha version

I'd be happy to suggest modifications to how they manage their releases, but wanted to start here so that if I do need to suggest a change to their project that it would align with this projects goals as well.

**Comment by jhnns** [comment]
You're right. Updtr should not touch these versions.

We already have a [check for this case](https://github.com/peerigon/updtr/blob/188fa49d58e11b87fe83c80907d17fe58a788603/lib/filter.js#L13) but it seems to fail in your scenario. Could you check why? And maybe submit a PR?

**Comment by travi** [comment]
I've been keeping an eye on this across several projects and haven't noticed the issue lately. I wonder if I simply had some node version through nvm that I hadn't updated for a while.

**Comment by jhnns** [comment]
Thx for checking
