### ISSUE TITLE
Don't update package.json if latest version is included in version range

### ISSUE THREAD

**Issue by mastertinner** [peerigon/updtr#46]
If I have dependencies of which the installed version is not up to date but the latest version is still included in the range which I have stated in my `package.json`, I would expect updtr not to write to my `package.json` but just update the installed version after a successful test instead. It's not necessary to write to the `package.json` in this case. That only creates unnecessary commits. We could also make this a flag for the CLI which defaults to the behavior described above. What do you guys think?

**Comment by jhnns** [comment]
Has been fixed with the rewrite
