### ISSUE TITLE
update prerelease versions

### ISSUE THREAD

**Issue by travi** [peerigon/updtr#51]
while i wouldn't want a stable version upgraded to a prerelease version or a prerelease version downgraded to a stable version, it would be valuable to have a prerelease version upgraded to a newer prerelease version.

**Comment by jhnns** [comment]
Has been fixed with the rewrite

**Comment by travi** [comment]
i don't think we mean the same thing if this is considered closed. i just verified that with `updtr` `v2.0.0`, i'm not getting updates for pre-releases published on non-`latest` channels, even when I am already depending on a pre-release.

in this case, the details are as follows:
* `npm outdated` shows 
  ```
  Package                         Current       Wanted  Latest 
  husky                       0.15.0-rc.8  0.15.0-rc.8  0.14.3
  ```
* `npm dist-tags ls husky` shows 
  ```
  latest: 0.14.3
  next: 0.15.0-rc.13
  ```
* running `updtr` outputs `● husky not-wanted` and does not update husky to `0.15.0-rc.13`

i'm not sure that this is a simple problem to solve, but the current behavior does not handle pre-releases like this as i was hoping.
