### ISSUE TITLE
Ability to run some command before, after and in between each upgraded package

### ISSUE THREAD

**Issue by mo** [peerigon/updtr#67]
For example, if I created a command "npm run print-webpack-bundle-size", I would like a way to tell updtr to run that command in between each package upgrade so I can keep track of which upgrades are causing my bundle.js to become bloated.

**Comment by jhnns** [comment]
Hi, that's a cool idea. I think, this should already be possible. You can pass a custom test command to updtr using the `-t` flag. So if you had a npm script that runs the test and then prints the webpack bundle size, that should be possible.
