### ISSUE TITLE
updtr eats my tabs in package.json and replaces it with spaces (npm)

### ISSUE THREAD

**Issue by moritzjacobs** [peerigon/updtr#68]
Awesome tool, I just have a small, very low priority issue with it: I use tabs in my `package.json` – I know, right? npm totally respects my decision, updtr does not, here's a reproducible testcase:

```sh
mkdir updtr-test
cd updtr-test
npm init --yes
```
gives us this package.json:

```js
{
  "name": "updtr-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```
Now remove the test (so updtr doesn't fail later) and entab:

```js
{
	"name": "updtr-test",
	"version": "1.0.0",
	"description": "",
	"main": "index.js",
	"scripts": {},
	"keywords": [],
	"author": "",
	"license": "ISC"
}
```

then `npm i del@2.2.2`, which is an old version. package.json looks like:

```js
{
	"name": "updtr-test",
	"version": "1.0.0",
	"description": "",
	"main": "index.js",
	"scripts": {},
	"keywords": [],
	"author": "",
	"license": "ISC",
	"dependencies": {
		"del": "^2.2.2"
	}
}
```
So tabs all the way. Nice. Now run `updtr`, lo and behold:

```js
{
  "name": "updtr-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "del": "^3.0.0"
  }
}
```
... we're back to 2 spaces, or as I call it: no indentation at all.

Nothing prettier doesn't solve for me, just a small issue. Great tool tho!

**Comment by jhnns** [comment]
Shipped with `v3.0.0` 🚀
