### ISSUE TITLE
exclude option is hard to understand

### ISSUE THREAD

**Issue by joh-klein** [peerigon/updtr#82]
The way `updtr --help` explains it, does not work for me:

`  --exclude, --ex       Space separated list of module names that should not be updated  [array]`

The only way I get it to work properly is by doing it this way:
`updtr --ex less --ex express`

**Comment by jhnns** [comment]
We're using [yargs to parse command-line arguments](https://github.com/yargs/yargs/blob/master/docs/api.md#arraykey). `updtr --ex less express` should work according to their documentation.

**Comment by joh-klein** [comment]
I am pretty sure, I tried that – I don't know why it didn't work then. It does work now, though. Sorry for the inconvenience!
